spring.application.name=product-service
spring.datasource.url=jdbc:postgresql://product-db:5432/product-db
spring.datasource.username=postgres
spring.datasource.password=Swift@5140
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
